src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 */
class Users
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @ORM\OneToMany(targetEntity="App\Entity\Pointages")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="integer")
     */
    private $matricule;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMatricule(): ?int
    {
        return $this->matricule;
    }

    public function setMatricule(int $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getIdentite()
    {
        return $this->nom . ' ' . $this->prenom;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
            <style>

                table {
                    width: 100%;
                    max-width: 100%;
                    margin-bottom: 20px;
                    border: 1px solid #ddd;
                    border-collapse: collapse;
                    border-spacing: 0;
                }

                table > thead > tr > th {
                    text-align:left;
                    border-bottom: 1px solid #ddd;
                    border-bottom-width: 2px;
                    padding: 8px;
                }

                table > tbody > tr > td {
                    border-bottom: 1px solid #ddd;
                    padding: 8px;
                }

                table > tbody > tr:nth-of-type(2n+1) {
                    background-color: #f9f9f9;
                }

                label {
                    display: inline-block;
                    max-width: 100%;
                    margin-bottom: 5px;
                    font-weight: 700;
                }

                select option:first-child{
                    color: #999;
                    opacity: 1;
                }

                select, input {
                    width:100%;
                    font-size: 14px;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
                    margin-bottom: 15px;
                }

                select {
                    height: 35px;
                }

                input {
                    height: 32px;
                }

                button[type=submit]
                {
                    padding: 6px 12px;
                    font-size: 14px;
                    border-radius: 4px;
                    cursor: pointer;
                    margin-bottom: 1em;
                }

            </style>
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/chantiers-edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <style>

        #chantiers_form_debut select {
            max-width:10%;
        }

    </style>
{% endblock %}

{% block title %}Gestion des chantiers{% endblock %}

{% block body %}
<style>

</style>

    <h1>Modifier un chantier</h1>

{{ form(formChantier) }}



{% endblock %}

templates/chantiers.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <style>

        #chantiers_form_debut select {
            max-width:10%;
        }

    </style>
{% endblock %}

{% block title %}Gestion des chantiers{% endblock %}

{% block body %}
<style>

</style>

    <h1>Ajouter un chantier</h1>

{{ form(formChantiers) }}

    <h1>Liste des chantiers</h1>

        <table>
            <thead>
                <th>ID</th>
                <th>Nom</th>
                <th>Adresse</th>
                <th>Date de début</th>
                <th>Nb de personnes</th>
                <th>Durée cumulée</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for chantier in chantiers %}
                <tr>
                    <td>{{ chantier.id }}</td>
                    <td>{{ chantier.nom }}</td>
                    <td>{{ chantier.adresse }}</td>
                    <td>{{ chantier.debut|date('d/m/Y') }}</td>
                    <td>{% if pointersByChantier[chantier.id] is defined %}
                            {{ pointersByChantier[chantier.id] }}
                        {% else %}
                            0
                        {% endif %}
                    </td>
                    <td>{% if dureesByChantier[chantier.id] is defined %}
                            {{ dureesByChantier[chantier.id]|slice(0, 5) }}
                        {% else %}
                            00:00
                        {% endif %}
                    </td>
                    <td><a href="{{ path('editChantier', {'id': chantier.id}) }}">Modifier</a></td>
                    <td><a href="{{ path('delChantier', {'id': chantier.id}) }}">Supprimer</a></td>
                </tr>
            {% else %} <tr><td colspan="8">Aucun chantier trouvé.</td></tr>
            {% endfor %}
            </tbody>
        </table>



{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acueil{% endblock %}

{% block body %}

    <h1>Bonjour !</h1>


    <h2> Choisissez une action : </h2>
    <h3>
        <ul>
            <li><a href="{{ path('users') }}">Gérer les utilisateurs</a></li>
            <li><a href="{{ path('chantiers') }}">Gérer les chantiers</a></li>
            <li><a href="{{ path('pointages') }}">Gérer les pointages</a></li>
        </ul>
    </h3>

{% endblock %}

templates/pointages-edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <style>

        #pointages_form_datePointage select, #pointages_form_dureePointage select {
            max-width:10%;
        }

    </style>
{% endblock %}

{% block title %}Gestion des pointages{% endblock %}

{% block body %}
<style>

</style>

    <h1>Modifier un pointage</h1>

{{ form(formPointage) }}



{% endblock %}

templates/pointages.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <style>

    #pointages_form_datePointage select, #pointages_form_dureePointage select {
        max-width:10%;
    }

    </style>
{% endblock %}

{% block title %}Gestion des pointages{% endblock %}

{% block body %}

    <h1>Ajouter un pointage</h1>

    <div id="erreurFormDbl"></div>
    <div id="erreurForm35h"></div>

{{ form(formPointages) }}

    <h1>Liste des pointages</h1>

        <table>
            <thead>
                <th>ID</th>
                <th>Nom de l'utilisateur</th>
                <th>Chantier</th>
                <th>Date du pointage</th>
                <th>Durée du pointage</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for pointage in pointages %}
                <tr>
                    <td>{{ pointage.id }}</td>
                    <td>{{ pointage.userId.identite }}</td>
                    <td>{{ pointage.chantierId.nom }}</td>
                    <td>{{ pointage.datePointage|date('d/m/Y') }}</td>
                    <td>{{ pointage.dureePointage|date('H:i') }}</td>
                    <td><a href="{{ path('editPointage', {'id': pointage.id}) }}">Modifier</a></td>
                    <td><a href="{{ path('delPointage', {'id': pointage.id}) }}">Supprimer</a></td>
                </tr>
            {% else %} <tr><td colspan="7">Aucun pointage trouvé.</td></tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>


$( document ).ready(function() {

        $('select').on('change', function() {
            let el = this;
            $('#pointages_form>ul').remove();

            let user = $('#pointages_form_userId').val();
            let chantier = $('#pointages_form_chantierId').val();

            let year = $('#pointages_form_datePointage_year').val();
            let month = ("0" + $('#pointages_form_datePointage_month').val()).slice(-2);
            let day = ("0" + $('#pointages_form_datePointage_day').val()).slice(-2);
            let date = year+'-'+month+'-'+day;

            let hour = ("0" + $('#pointages_form_dureePointage_hour').val()).slice(-2);
            let minute = ("0" + $('#pointages_form_dureePointage_minute').val()).slice(-2);
            let duree = hour+':'+minute;

            if(el.parentElement.id !== 'pointages_form_dureePointage'
                && user > 0
                && chantier > 0
                && date.length === 10) {
                    checkPointageDoublon(user, chantier, date);
            }

            if(el.id !== 'pointages_form_chantierId'
                && user > 0
                && date.length === 10
                && duree.length === 5) {
                    checkPointage35h(user, date, duree);
            }

        });

});

function checkPointageDoublon(user, chantier, date) {

    $.ajax({
                url: '{{ path('checkPointageDoublon') }}',
                method: 'POST',
                data: { user:user, chantier:chantier, date:date },
                timeout: 20000,
                success: function(result) {
                    if(result) {
                        $('#erreurFormDbl').html('Cet utilisateur a déjà été pointé sur ce chantier pour cette journée.');
                        $("#pointages_form_submit"). attr("disabled", true);
                    }
                    else {
                        $('#erreurFormDbl').html('')
                        if($('#erreurForm35h').html() === '') $("#pointages_form_submit"). attr("disabled", false);
                    }
                },
                error: function(){
                    window.location.reload();
                }
            });

}

function checkPointage35h(user, date, duree) {

    $.ajax({
        url: '{{ path('checkPointage35h') }}',
        method: 'POST',
        data: { user:user, date:date, duree:duree },
        timeout: 20000,
        success: function(result) {
            if(result) {
                $('#erreurForm35h').html('Cet utilisateur ne peut pas dépasser les 35H pour cette semaine');
                $("#pointages_form_submit"). attr("disabled", true);
            }
            else {
                $('#erreurForm35h').html('');
                if($('#erreurFormDbl').html() === '') $("#pointages_form_submit"). attr("disabled", false);
            }
        },
        error: function(){
            window.location.reload();
        }
    });

}



    </script>
{% endblock %}

templates/users-edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des utilisateurs{% endblock %}

{% block body %}
<style>

</style>

    <h1>Modifier un utilisateur</h1>

{{ form(formUser) }}



{% endblock %}

templates/users.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des utilisateurs{% endblock %}

{% block body %}
<style>

</style>

    <h1>Ajouter un utilisateur</h1>

{{ form(formUsers) }}

    <h1>Liste des utilisateurs</h1>

        <table>
            <thead>
                <th>ID</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Matricule</th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.nom }}</td>
                    <td>{{ user.prenom }}</td>
                    <td>{{ user.matricule }}</td>
                    <td><a href="{{ path('editUser', {'id': user.id}) }}">Modifier</a></td>
                    <td><a href="{{ path('delUser', {'id': user.id}) }}">Supprimer</a></td>
                </tr>
            {% else %} <tr><td colspan="6">Aucun utilisateur trouvé.</td></tr>
            {% endfor %}
            </tbody>
        </table>



{% endblock %}